#! /usr/bin/bash

schedule (){
	while [ true ]; do
		time=$(date +%${1})
		if [ ${time} -eq $2 ]; then
			shutdown
			exit 1
		fi
		echo -ne "\r${time} "
	done
}

unit=$1
alarm=$2
msg="please enter flag followed by a 2-digit number (shutdown time)\nflags: -h (hours) -m (minutes) -s (seconds)\ne.g ./off -h 3"
if [[ "$2" =~ ^[0-9]+$ ]] && [ ${#2} -eq 2 ]; then
	if [ "$1" == "-h" ]; then
		schedule "H" "$2"
	elif [ "$1" == "-m" ]; then
		schedule "M" "$2"
	elif [ "$1" == "-s" ]; then
		schedule "S" "$2"
	else
		echo -e $msg
	fi
else
	echo -e $msg
fi


