#!/bin/zsh

# Comment

echo "Hello world"
# chmod 755

# variables

myName="Kori"

# constant

declare -r NUM1=5
num2=4
num3=$((NUM1+num2))

echo "$((num3))"
echo "$((6 + 6))"

rand=5
let rand+=4
echo "$rand"
echo "rand++ = $(( ++rand ))"

cat<< END
This text
tries to
be great
END
